### ISSUE TITLE
@SceneEditor: arcade body bug or maybe only misconception?

### ISSUE THREAD

**Issue by ponderboy** [boniatillo-com/PhaserEditor#20] opened 2017-02-19 14:09 UTC
I was using the arcade body on a sprite that has an edited anchor point. When editing the arcade body (to center it and make it smaller) that seems to not get into account. 

I was wondering why there was a gap when colliding. By debugging the body I realized it is not layout like I've seen it in the SceneEditor. It surely is a phaser thing that you will have to take the changed anchor points into account. But it is irritating, when you don't see it like that in the editor. 

I hope it was understandable. I was adjusting it now by trial and error. Which was okay but I was testing several other coding things before it dawned to me..

**Comment by boniatillo-com** [comment] 2017-02-20 14:31
Please can you share a screenshot? Are you sure there is not any other field changed like the `pivot` for example?

If you create a project based on the **Main Templates > Platformer** you will see the Dino character has a reduced body and an anchor, and it works well.

**Comment by ponderboy** [comment] 2017-02-20 14:53
Here I debug the body:

![preview](https://cloud.githubusercontent.com/assets/5340556/23129786/51356c62-f784-11e6-95b0-77b1166453e2.png)


And here is, how I set it up in the editor:

![editor](https://cloud.githubusercontent.com/assets/5340556/23129785/51344c6a-f784-11e6-8e71-54c95c6be31a.png)

**Comment by boniatillo-com** [comment] 2017-02-20 19:41
Please test [this project](https://dl.dropboxusercontent.com/u/100685682/Phaser%20Editor/SupportFiles/AnchorBodyDemo.zip) It is a simple demo trying to reproduce your game. In this demo it works. Look how the body is the same in the scene and in the game. I cannot reproduce the bug. Please look again in your code maybe the body is changed in other place.

(In the demo I send you here you can move with the arrow keys)

![Body in canvas](https://dl.dropboxusercontent.com/u/100685682/Phaser%20Editor/SupportFiles/DemoCanvasScreenshot.jpg)

![Body in game](https://dl.dropboxusercontent.com/u/100685682/Phaser%20Editor/SupportFiles/DemoScreenshot.jpg)

Project with source: https://dl.dropboxusercontent.com/u/100685682/Phaser%20Editor/SupportFiles/AnchorBodyDemo.zip

**Comment by ponderboy** [comment] 2017-02-21 19:39
Yes, you demo works... I have no clue. Seriously. At the moment I have the feeling the whole file is sort of corrupt or set up badly... 

It's a pity though, especially time wise, but I guess I will rebuild it again. I'll let you know then. Thanks a lot for your replies and time!

**Comment by boniatillo-com** [comment] 2017-02-21 19:55
You are welcome, for me it is very important to find any issue with the editor, to deliver a robust product the feedback is essential. So please do not hesitate to contact with us if you find any issue.

If you like I can look inside your project/code and things like that.

**Comment by boniatillo-com** [comment] 2017-02-21 19:56
I will keep this issue open for a time, maybe we find a clue :)

**Comment by ponderboy** [comment] 2017-02-23 16:36
After cleaning the Project, the body was aligned properly or wrongly in my case which is correct for the editor. 
In other words it's not an issue anymore.

**Comment by boniatillo-com** [comment] 2017-02-23 16:54
Great, in the next version all the auto-build/clean stuff is going to be more robust. I close this.

**Closed by boniatillo-com** 2017-02-23 16:54 UTC
Labels: bug, canvas
