### ISSUE TITLE
I again broke the canvas... could need some help

### ISSUE THREAD

**Issue by ponderboy** [boniatillo-com/PhaserEditor#22] opened 2017-02-21 19:18 UTC
Well, I just pasted my atlas file over the existing and now I have this:

`org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/Stoer/WebContent/assets/scenes/Scene1.canvas'.`

Last time it was just a wrong name in the atlas xml file. But now I have no clue, how to recover that. 

I also have no clue how to setup a backup strategy routine for phasereditor as well. By now I was copying my folder to another location and putting a date on it. But when I try to use one backed up folder. I get the same message.

**Comment by ponderboy** [comment] 2017-02-21 19:36
No idea... 
I opened the editor up again. Imported another file and somehwo my scene is now there again... 

For the moment my workflow is doing the scene with phasereditor but then code with sublime. Therefore I just copy the Scene.js file over. Unfortunately sometimes errors are sneaking in every now and then... 

So feel free to delete this issue or maybe provide a way for the next time?! But I can't reproduce.

**Comment by boniatillo-com** [comment] 2017-02-21 19:41
Try closing the canvas file and refreshing the workspace. To refresh the workspace select all in the Project Explorer and press F5.

Resources out of sync mean files that was modified by an external program so you need to refresh the state of those file inside Eclipse.

Also I recommend when something like this happen to clean/rebuild the workspace. In the main menu click on `Project > Clean...` and select the projects you want to clean.

Tell me if it worked to you.

**Comment by boniatillo-com** [comment] 2017-02-21 19:45
Ah, I see it was fixed.

I understand your frustration. It is just to get used to how the Eclipse works.

As you said, you are doing external modifications. By default the editor should realize of external changes but it can fail, when something goes wrong after an external modification just do what I recommended to you:

- Refresh the workspace
- Clean/rebuild the projects

If you want to reproduce the error you can try by modifying the canvas file outside the Phaser Editor, then try to save it in the editor, you will get the error, so you have to refresh and reopen it.

Can I close this?

**Comment by samsstuff** [comment] 2017-02-22 06:47
> I understand your frustration. It is just to get used to how the Eclipse works.

this is how eclipse worked for java and android also, it's just the way it is.
adding files by copy pasting them into a project, while the project is open, can cause it, not importing through eclipse can cause it, and sometimes importing without refreshing or cleaning the project can cause it
probably because it doesn't write to the metadata files right away and gets confused
with android changing lines in gradle code causes errors almost every time if you don't clean the project.
One of the best tips for eclipse boniatillo gave you
refresh and clean, most times just cleaning the project does the trick.

**Comment by boniatillo-com** [comment] 2017-02-22 12:40
However in the next release the editor will be more robust, with the new refactoring tools.

**Comment by ponderboy** [comment] 2017-02-23 16:39
Thanks, that information on eclipse and cleaning the project worked for me. 
Maybe I overlooked it or it should be documented somewhere more obvious.

**Comment by boniatillo-com** [comment] 2017-02-23 16:56
Yes, it should be more documented. We need to write a Troubleshooting Guide.

Thanks you.

**Closed by boniatillo-com** 2017-02-23 16:56 UTC
